name: Y Auto Uploader
on:
  workflow_dispatch:
    inputs:
      file_url:
        required: true
      file_name:
        required: true
        default: 'video'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run
        env:
          URL: ${{ github.event.inputs.file_url }}
          NAME: ${{ github.event.inputs.file_name }}
          CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
        run: |
          pip install yt-dlp google-api-python-client google-auth-oauthlib
          echo "$CREDENTIALS" > client_secrets.json
          yt-dlp "$URL" -o "video.mp4"
          python upload.py
